name: Build and Release DEB Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build with Cargo
        run: make build

      - name: Build DEB package
        run: make deb

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files:
            bm_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
